phrases = [
    "{user_1} meat died and he/she decided to have a **funural** in {user_2} butthole :love_you_gesture:",
    "{user_1} dropped the **soap** for {user_2} to pick up :thinking:",
    "{user_1} wants to send bobs and **vagin** to {user_2} :nerd:",
    "{user_1} wants to **cuddle** {user_2} :heart_eyes:",
    "{user_1} knows what needs to be done but {user_2} does not know he has the strenght to do it :weary:",
    "{user_1} More!!!!! {user_2} More !!!!! :banana:",
    "{user_1} wants to suck a whole **mattress** in {user_2} butthole ",
    "{user_1} I have a good K/D in **Warzone** {user_2} let the carring begin",
    "{user_1} How many black people does it take to start a **race war**? {user_2} -1",
    "{user_1} wants to show {user_2} some dank **memes**",
    "{user_1} What is an universal Russian word? {user_2} **Suka Blyat**, i don't know either",
    "{user_1} wants to invite {user_2} for some **netflix** and chill",
    "{user_1} wants to invite {user_2} over for some Surströmming",
    "{user_1} wants to invite {user_2} over for some grandmother's baba **ganoush**",
    "{user_1} wants to invite {user_2} over for some Sauerkraut",
    "{user_1} wants to start a descusion with {user_2} about pineapple on **pizza**",
    "{user_1} fancies {user_2} small **pipi**",
    "{user_1} wants to bitch **slap** {user_2}",
    "{user_1} wants to toosie slide in {user_2} DM's",
    "{user_1} had a wonderfull expierence with {user_2}",
    "{user_1} did a flap slap on{user_2}",
    "{user_1} wants to share a song with {user_2} about rich white people that are in love, struggle with feelings and want to run away from there parents",
    "{user_1} is asking {user_2} to look in the **glory hole**",
    "{user_1} wants to show {user_2} da way",
    "{user_1} want to invite {user_2} to a **TEA bag** session",
    "{user_1} knocks on the door, to enlight {user_2} about the **Jehovah** religion",
    "{user_1} want to show a video to {user_2} about mom's getting stuck in there **household** machines",
    "{user_1} is inviting {user_2} to watch 2 girls **one cup**",
    "{user_1} wants to bake a **haircake** with {user_2}",
    "{user_1} wants to **hug** a three with {user_2}",
    "{user_1} doesn't care if {user_2} is still **listening a song** in 2020",
    "{user_1} wants to give {user_2} some **squirrel** aids",
    "{user_1} wants to kick {user_2} in the **nuts**, for saying \"i was born in the wrong year\"",
    "{user_1} doesn't like the marketing strategy of {user_2}  \"if you don't like it don't buy it\"",
    "{user_1} wants to tell {user_2} more about his black, **LGTB** aunt in a weelchair who fought Nazis in WWII",
    "{user_1} wants to clap some **cheeks** with {user_2}",
    "{user_1} doens't find it oké if {user_2} is insluting and **admin**",
    "{user_1} wants to ask {user_2} a question",
    "{user_1} wants to speak to {user_2}'s **manager**",
    "{user_1} is inviting {user_2} over for a bath, filled with gamer girl **bathwater**",
    "{user_1} wants to speak croisant with {user_2}",
    "{user_1} is asking {user_2} not to break is achy **breaky heart**",
    "{user_1} wants to **rick roll** with {user_2}",
    "{user_1} wants to **Cheeki Breeki** with {user_2}",
    "{user_1} wants to show {user_2} some curd loving video's form **italy**",
    "{user_1} wants to show {user_2} some cool next level **vape tricks**",
    "{user_1} wants to show {user_2} around in the **GAY**berhood",
    "{user_1} is inviting {user_2} over for some Belgian **Fries**",
    "{user_1} wants to follow {user_2} to the **Mother land**",
    "{user_1} is inviting {user_2} for a Cockhold session with his **wife**",
    "{user_1} is bringing a **tent** over for {user_2} to camp in.",
    "{user_1} feels sorry for the **turret** kill on {user_2}",
    "{user_1} is trying to excite {user_2} with his **belly dance**",
    "{user_1} eating {user_2}'s poop. It's so **tasty**!",
    "{user_1} looks into {user_2}'s **beautiful eyes** and waits for the night",
    "{user_1} wants to take some radiation **pills** with {user_2}",
    "{user_1} likes {user_2}'s big **boobs**",
    "{user_1} likes {user_2}'s big **nuts**",
    "{user_2} admires {user_1}'s shaved **scrotum**",
    "{user_1} bites {user_2} neck",
    "{user_1} gives {user_2} his black dildo. Do not forget to return!",
    "{user_1} calls {user_2}: Hey f-ckin **noob**, look at me!",
    "{user_1} wants to nibbel on {user_2} 's third nipple",
    "{user_1} wants to 'how to basic' {user_2} his playground",
    "{user_1} is inviting {user_2} over, for a **play date**",
    "{user_1} wants to grap a 'cold one' with {user_2}"
    "{user_1} wants to tell {user_2} more about the mutiple uses of a **cucumber** plant (ask Issa :shh:)",
    "{user_1} wants {user_2} to push **harder**",
    "{user_1} is waiting on {user_2} to say '**Que rico papi**, que rico'",
    "{user_1} would love to **bake** a vomit cake with {user_2}",
    "{user_1} wants {user_2} to be more then only a parttime lover",
    "{user_1} wants {user_2} to put the Strapon on",
    "{user_1} wants to show {user_2} something special, underneath the **moonlight**",
    "{user_1} wants to share some dirty **buttcrack** pics with {user_2}",
    "{user_1} wants to **nibble** on the ballsack of {user_2}",
    "{user_1} has something in his **front pocket** for {user_2}",
    "{user_1} wants to **fingerpaint** {user_2} asshole",
    "{user_1} wants **to smoke** a three with {user_2}",
    "{user_1} would for sure **superlike** {user_2} on Tinder"
]
